name = "Tables"
version = "0.1.0"
defaultTargets = ["tables"]

[leanOptions]
autoImplicit = false

[[require]]
name = "batteries"
scope = "leanprover-community"
rev = "main"

[[lean_lib]]
name = "Tables"

[[lean_exe]]
name = "tables"
root = "Main"
